# Generated by Django 6.0.3 on 2026-03-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home_auth', '0002_customuser_is_authorized_customuser_login_token_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordresetrequest',
            name='token',
            field=models.CharField(default='JErG4ZOYgb7D05nT92rIugeUDegkrGDT', editable=False, max_length=32, unique=True),
        ),
    ]
